### ISSUE TITLE
How do you run a function on instantiation? 

### ISSUE THREAD

**Issue by dderiso** [replit/jq-console#87]
Awesome project, thanks for this! Is there any way to preload the terminal with code so that the user can use variables right away? Thanks!

**Comment by masad-frost** [comment]
I'm not sure what you mean. The console doesn't run functions or store
variables, it just handles input and output. Your engine should handle
these things.

I guess the only thing you can do is use SetPromptText after instantiating
and load up the vars, then the user would have to press enter. Again,
that's assuming assuming your engine handles the entered prompt/input.

Awesome project, thanks for this! Is there any way to preload the terminal
with code so that the user can use variables right away? Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/replit/jq-console/issues/87>.

**Comment by dderiso** [comment]
Got it, thanks for the quick reply :)

**Comment by dderiso** [comment]
Got it to work using 2 approaches. One approach is to add the variable to window:
```
window.some_function = function() { return 1; };
```

Another approach is to enter the string to evaluate as you helpfully suggested and then register an enter:

```
jqconsole.SetPromptText("a = 1");
jqconsole._HandleEnter(false);
```
